tests: Specify locales' charsets explicitly, fixing FTBFS with new glibc
glibc 2.31-14 dropped support for all non-UTF-8 locales, so we can't
use /usr/share/i18n/SUPPORTED to choose a suitable charset any more.

diff --git a/debian/tests/run-with-locales b/debian/tests/run-with-locales
--- a/debian/tests/run-with-locales
+++ b/debian/tests/run-with-locales
@@ -3,9 +3,10 @@
 # Run a wrapped command with at least the requested locales available.
 # Requires a dependency on locales | locales-all.
 # The requested locales must be of the form foo_FOO.utf8, or special-cased
-# in generate().
+# in generate(), or listed in /usr/share/i18n/SUPPORTED, or specify the
+# locale in the form locale=charset.
 #
-# Copyright 2016-2020 Simon McVittie
+# Copyright 2016-2021 Simon McVittie
 # Copyright 2017-2018 Collabora Ltd.
 #
 # SPDX-License-Identifier: MIT
@@ -57,13 +58,18 @@ unset getopt_temp
 
 generate () {
     local locale="$1"
-    local charset
+    local charset=""
     local source
     local output
 
     echo "$me: $locale..." >&2
 
     case "$locale" in
+        (*=*)
+            source="${locale%=*}"
+            output="$source"
+            ;;
+
         (*.*)
             source="${locale%.*}"
             output="$source.$(
@@ -84,18 +90,27 @@ generate () {
         return
     fi
 
+    if ! [ -d /usr/share/i18n/charmaps ]; then
+        echo "$me: $locale not in locales-all and /usr/share/i18n/charmaps not found" >&2
+        return
+    fi
+
     case "$locale" in
-        (*.utf8)
+        (*=*)
+            charset="${locale##*=}"
+            ;;
+
+        (*.utf8 | *.UTF-8)
             charset="UTF-8"
             ;;
 
-        (*)
-            charset=$(sed -ne "s/^$locale //p" /usr/share/i18n/SUPPORTED)
+        (*.*)
+            charset="${locale##*.}"
             ;;
     esac
 
     if [ -z "$charset" ]; then
-        echo "$me: $locale not found in /usr/share/i18n/SUPPORTED" >&2
+        echo "$me: $locale charset not known" >&2
         exit 1
     fi
 
