* update-icon-caches: always exit with a 0 code to avoid breaking   upgrades when a cache is corrupt. Display a big fat warning instead.   Closes: #466083.

diff --git a/debian/update-icon-caches b/debian/update-icon-caches
--- a/debian/update-icon-caches
+++ b/debian/update-icon-caches
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-set -e
-
 case "$1" in
     ""|-h|--help)
         echo "Usage: $0 directory [ ... ]"
@@ -16,7 +14,9 @@ for dir in "$@"; do
     if [ -f "$dir"/index.theme ]; then
         if [ -f "$dir"/icon-theme.cache ]; then
             # The cache already exists, regenerate it
-            gtk-update-icon-cache --force --quiet "$dir"
+            if ! gtk-update-icon-cache --force --quiet "$dir"; then
+                echo "WARNING: icon cache generation failed for $dir"
+            fi
         fi
     else
         # No more index.theme, remove the cache if it exists
@@ -25,3 +25,4 @@ for dir in "$@"; do
     fi
 done
 
+exit 0
